name: Staging CI/CD

on:
  push:
    branches:
      - staging

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet publish -c Release -o ./publish

      - name: Compress build artifacts
        run: zip -r publish.zip ./publish

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: publish-artifact
          path: publish.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: publish-artifact

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_STAGING_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3
        with: 
          app-name: ${{ secrets.AZURE_APP_NAME_STAGING }}
          package: ./publish.zip
